# Generated by Django 5.1.4 on 2024-12-10 20:25

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0002_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='body',
            field=models.TextField(default=''),  # Fixed: Use an empty string as the default
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),  # Fixed: Remove invalid default
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
